// <auto-generated />
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(CompetitionEntities))]
    [Migration("20240704104346_Revision_Competitors")]
    partial class Revision_Competitors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Competition", b =>
                {
                    b.Property<int>("CompetitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CompetitionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Competition");

                    b.HasData(
                        new
                        {
                            CompetitionId = 1,
                            Name = "Competition_1"
                        },
                        new
                        {
                            CompetitionId = 2,
                            Name = "Competition_2"
                        },
                        new
                        {
                            CompetitionId = 3,
                            Name = "Competition_3"
                        },
                        new
                        {
                            CompetitionId = 4,
                            Name = "Competition_4"
                        },
                        new
                        {
                            CompetitionId = 5,
                            Name = "Competition_5"
                        },
                        new
                        {
                            CompetitionId = 6,
                            Name = "Competition_6"
                        },
                        new
                        {
                            CompetitionId = 7,
                            Name = "Competition_7"
                        },
                        new
                        {
                            CompetitionId = 8,
                            Name = "Competition_8"
                        },
                        new
                        {
                            CompetitionId = 9,
                            Name = "Competition_9"
                        },
                        new
                        {
                            CompetitionId = 10,
                            Name = "Competition_10"
                        },
                        new
                        {
                            CompetitionId = 11,
                            Name = "Competition_11"
                        },
                        new
                        {
                            CompetitionId = 12,
                            Name = "Competition_12"
                        },
                        new
                        {
                            CompetitionId = 13,
                            Name = "Competition_13"
                        },
                        new
                        {
                            CompetitionId = 14,
                            Name = "Competition_14"
                        },
                        new
                        {
                            CompetitionId = 15,
                            Name = "Competition_15"
                        },
                        new
                        {
                            CompetitionId = 16,
                            Name = "Competition_16"
                        },
                        new
                        {
                            CompetitionId = 17,
                            Name = "Competition_17"
                        },
                        new
                        {
                            CompetitionId = 18,
                            Name = "Competition_18"
                        },
                        new
                        {
                            CompetitionId = 19,
                            Name = "Competition_19"
                        },
                        new
                        {
                            CompetitionId = 20,
                            Name = "Competition_20"
                        });
                });

            modelBuilder.Entity("Entities.Competitor", b =>
                {
                    b.Property<int>("CompetitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitorId"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CompetitorId");

                    b.HasIndex("CompetitionId", "Name")
                        .IsUnique();

                    b.ToTable("Competitors");

                    b.HasData(
                        new
                        {
                            CompetitorId = 1,
                            CompetitionId = 1,
                            Name = "Karl_1"
                        },
                        new
                        {
                            CompetitorId = 2,
                            CompetitionId = 1,
                            Name = "Bertil_1"
                        },
                        new
                        {
                            CompetitorId = 3,
                            CompetitionId = 2,
                            Name = "Karl_2"
                        },
                        new
                        {
                            CompetitorId = 4,
                            CompetitionId = 2,
                            Name = "Bertil_2"
                        },
                        new
                        {
                            CompetitorId = 5,
                            CompetitionId = 3,
                            Name = "Karl_3"
                        },
                        new
                        {
                            CompetitorId = 6,
                            CompetitionId = 3,
                            Name = "Bertil_3"
                        },
                        new
                        {
                            CompetitorId = 7,
                            CompetitionId = 4,
                            Name = "Karl_4"
                        },
                        new
                        {
                            CompetitorId = 8,
                            CompetitionId = 4,
                            Name = "Bertil_4"
                        },
                        new
                        {
                            CompetitorId = 9,
                            CompetitionId = 5,
                            Name = "Karl_5"
                        },
                        new
                        {
                            CompetitorId = 10,
                            CompetitionId = 5,
                            Name = "Bertil_5"
                        },
                        new
                        {
                            CompetitorId = 11,
                            CompetitionId = 6,
                            Name = "Karl_6"
                        },
                        new
                        {
                            CompetitorId = 12,
                            CompetitionId = 6,
                            Name = "Bertil_6"
                        },
                        new
                        {
                            CompetitorId = 13,
                            CompetitionId = 7,
                            Name = "Karl_7"
                        },
                        new
                        {
                            CompetitorId = 14,
                            CompetitionId = 7,
                            Name = "Bertil_7"
                        },
                        new
                        {
                            CompetitorId = 15,
                            CompetitionId = 8,
                            Name = "Karl_8"
                        },
                        new
                        {
                            CompetitorId = 16,
                            CompetitionId = 8,
                            Name = "Bertil_8"
                        },
                        new
                        {
                            CompetitorId = 17,
                            CompetitionId = 9,
                            Name = "Karl_9"
                        },
                        new
                        {
                            CompetitorId = 18,
                            CompetitionId = 9,
                            Name = "Bertil_9"
                        },
                        new
                        {
                            CompetitorId = 19,
                            CompetitionId = 10,
                            Name = "Karl_10"
                        },
                        new
                        {
                            CompetitorId = 20,
                            CompetitionId = 10,
                            Name = "Bertil_10"
                        },
                        new
                        {
                            CompetitorId = 21,
                            CompetitionId = 11,
                            Name = "Karl_11"
                        },
                        new
                        {
                            CompetitorId = 22,
                            CompetitionId = 11,
                            Name = "Bertil_11"
                        },
                        new
                        {
                            CompetitorId = 23,
                            CompetitionId = 12,
                            Name = "Karl_12"
                        },
                        new
                        {
                            CompetitorId = 24,
                            CompetitionId = 12,
                            Name = "Bertil_12"
                        },
                        new
                        {
                            CompetitorId = 25,
                            CompetitionId = 13,
                            Name = "Karl_13"
                        },
                        new
                        {
                            CompetitorId = 26,
                            CompetitionId = 13,
                            Name = "Bertil_13"
                        },
                        new
                        {
                            CompetitorId = 27,
                            CompetitionId = 14,
                            Name = "Karl_14"
                        },
                        new
                        {
                            CompetitorId = 28,
                            CompetitionId = 14,
                            Name = "Bertil_14"
                        },
                        new
                        {
                            CompetitorId = 29,
                            CompetitionId = 15,
                            Name = "Karl_15"
                        },
                        new
                        {
                            CompetitorId = 30,
                            CompetitionId = 15,
                            Name = "Bertil_15"
                        },
                        new
                        {
                            CompetitorId = 31,
                            CompetitionId = 16,
                            Name = "Karl_16"
                        },
                        new
                        {
                            CompetitorId = 32,
                            CompetitionId = 16,
                            Name = "Bertil_16"
                        },
                        new
                        {
                            CompetitorId = 33,
                            CompetitionId = 17,
                            Name = "Karl_17"
                        },
                        new
                        {
                            CompetitorId = 34,
                            CompetitionId = 17,
                            Name = "Bertil_17"
                        },
                        new
                        {
                            CompetitorId = 35,
                            CompetitionId = 18,
                            Name = "Karl_18"
                        },
                        new
                        {
                            CompetitorId = 36,
                            CompetitionId = 18,
                            Name = "Bertil_18"
                        },
                        new
                        {
                            CompetitorId = 37,
                            CompetitionId = 19,
                            Name = "Karl_19"
                        },
                        new
                        {
                            CompetitorId = 38,
                            CompetitionId = 19,
                            Name = "Bertil_19"
                        },
                        new
                        {
                            CompetitorId = 39,
                            CompetitionId = 20,
                            Name = "Karl_20"
                        },
                        new
                        {
                            CompetitorId = 40,
                            CompetitionId = 20,
                            Name = "Bertil_20"
                        });
                });

            modelBuilder.Entity("Entities.Competitor", b =>
                {
                    b.HasOne("Entities.Competition", null)
                        .WithMany("Competitors")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Competition", b =>
                {
                    b.Navigation("Competitors");
                });
#pragma warning restore 612, 618
        }
    }
}
